# -*- coding: utf-8 -*-
from pathlib import Path
path = Path('script.js')
text = path.read_text(encoding='utf-8')
old1 = "      ${!isPro ? `\r\n        <div style=\"margin-top:18px;display:flex;justify-content:center;\">\r\n          <div style=\"background:linear-gradient(135deg,#1b5e20 0%,#2e7d32 100%);color:#fff;padding:18px 22px;border-radius:14px;box-shadow:0 10px 18px rgba(0,0,0,0.18);max-width:420px;width:100%;text-align:left;\">\r\n            <strong style=\"display:block;font-size:17px;margin-bottom:6px;\">💡 Acesso completo às provas</strong>\r\n            <span style=\"display:block;font-size:15px;line-height:1.45;\">Fale com seu instrutor ou responsável no CFC e solicite a liberação total dos simulados.</span>\r\n          </div>\r\n        </div>` : \"\"}\r\n      <div style=\"display:flex;justify-content:center;margin-top:30px;\">\r\n        <button type=\"button\" class=\"auth-btn auth-link\" style=\"width:100%;max-width:360px;\" data-back=\"simulados\" data-back-screen=\"simulados\">Voltar</button>\r\n      </div>\r\n"
old2 = "      ${!isPro ? `\r\n        <div style=\"margin-top:18px;display:flex;justify-content:center;\">\r\n          <div style=\"background:linear-gradient(135deg,#1b5e20 0%,#2e7d32 100%);color:#fff;padding:18px 22px;border-radius:14px;box-shadow:0 10px 18px rgba(0,0,0,0.18);max-width:420px;width:100%;text-align:left;\">\r\n            <strong style=\"display:block;font-size:17px;margin-bottom:6px;\">💡 Acesso completo às provas</strong>\r\n            <span style=\"display:block;font-size:15px;line-height:1.45;\">Fale com seu instrutor ou responsável no CFC e solicite a liberação total dos simulados.</span>\r\n          </div>\r\n        </div>` : ''}\r\n      <div style=\"display:flex;justify-content:center;margin-top:30px;\">\r\n        <button type=\"button\" class=\"auth-btn auth-link\" style=\"width:100%;max-width:360px;\" data-back=\"simulados\" data-back-screen=\"simulados\">Voltar</button>\r\n      </div>\r\n"
new_block = "      <div style=\"display:flex;justify-content:center;margin-top:30px;\">\r\n        <button type=\"button\" class=\"auth-btn auth-link\" style=\"width:100%;max-width:360px;\" data-back=\"simulados\" data-back-screen=\"simulados\">Voltar</button>\r\n      </div>\r\n      ${!isPro ? `\r\n        <div style=\"margin-top:24px;display:flex;justify-content:center;\">\r\n          <div style=\"background:linear-gradient(135deg,#2ecc71 0%,#1e8a3d 100%);color:#fff;padding:20px 26px;border-radius:18px;box-shadow:0 18px 36px rgba(0,0,0,0.28);max-width:440px;width:100%;text-align:left;border:1px solid rgba(255,255,255,0.4);\">\r\n            <strong style=\"display:block;font-size:18px;margin-bottom:8px;\">💡 Libere o acesso total</strong>\r\n            <span style=\"display:block;font-size:15px;line-height:1.5;\">Fale com seu instrutor ou responsável no CFC e solicite a liberação completa dos simulados para estudar sem limites.</span>\r\n          </div>\r\n        </div>`"
if old1 not in text or old2 not in text:
    raise SystemExit('pattern not found')
text = text.replace(old1, new_block + " : \"\"}\r\n", 1)
text = text.replace(old2, new_block + " : ''}\r\n", 1)
path.write_text(text, encoding='utf-8')
